services:
  manager:
    volumes:
      - ./config/config.prod.yaml:/app/config/config.yaml:ro

  proxy:
    volumes:
      - ./config/config.prod.yaml:/app/config/config.yaml:ro

  handler:
    volumes:
      - ./config/config.prod.yaml:/app/config/config.yaml:ro
