version: "3.9"
services:
  handler:
    build:
      context: .
      dockerfile: services/handler/Dockerfile
    image: weaver-handler
    container_name: weaver_handler
    network_mode: host
    cap_add: ["NET_ADMIN", "NET_RAW"]
    volumes:
      - ./config:/app/config:ro
    environment:
      - WEAVER_CONFIG=/app/config/config.yaml
    init: true
    restart: unless-stopped
    stop_grace_period: 10s

  proxy:
    build:
      context: .
      dockerfile: services/proxy/Dockerfile
    image: weaver-proxy
    container_name: weaver_proxy
    network_mode: host
    cap_add: ["NET_ADMIN"]
    volumes:
      - ./config:/app/config:ro
    environment:
      - WEAVER_CONFIG=/app/config/config.yaml
      - PROXY_CFG=/app/config/3proxy.cfg
    init: true
    restart: unless-stopped
    stop_grace_period: 10s

  manager:
    build:
      context: .
      dockerfile: services/manager/Dockerfile
    image: weaver-manager
    network_mode: "host"
    cap_add: ["NET_ADMIN","NET_RAW"]
    restart: "no"
    volumes:
      - ./config:/app/config
      - ./state:/app/state
