global:
  state_file_path: /app/state/state.json
  proxy_config_path: /usr/local/3proxy/conf/3proxy.cfg
  ipv6_interface: eth0
  inbound_ipv4_address: "0.0.0.0"
  log_level: INFO
  egress_bind: "auto"      # "auto" | "off"
  pinned_ipv6: []          # список /128, которые нельзя удалять

observability:
  health_bind: "127.0.0.1:9090"
  health_interval_sec: 60

proxy_groups:
  - name: pool1
    ipv6_subnet: "2a01:4f8:c0c:1234::/64"
    count: 100
    proxy_type: "http"         # http | socks5
    port_range: { start: 30000, end: 30099 }
    nfqueue_num: 0             # null/отсутствует => не наблюдать эту группу (правило не ставим)
    persona: null              # для совместимости поля, не используется в safe-режиме
