global:
  state_file_path: /app/state/state.json
  proxy_config_path: /app/config/3proxy.cfg
  ipv6_interface: eth0
  inbound_ipv4_address: "0.0.0.0"

# Наблюдаемость
observability:
  health_bind: "127.0.0.1:9090"
  health_interval_sec: 60

# Настройки handler'а
handler:
  # ВНИМАНИЕ: оставить false. Подмены пакетов не выполняем.
  modify_packets: false

# Персоны (примерные поля для валидации/телеметрии; НЕ реальные отпечатки)
personas:
  example_android_14:
    ttl: 64
    window_size: 65535
  example_ios_17:
    ttl: 64
    window_size: 65535
  example_windows_11:
    ttl: 128
    window_size: 64240
  example_ubuntu_22_04:
    ttl: 64
    window_size: 29200

# Группы прокси (пример)
proxy_groups:
  - name: "android-pool-1"
    ipv6_subnet: "2a01:4f8:c0c:1234::/64"
    count: 1000
    proxy_type: "http"
    port_range: { start: 30000, end: 30999 }
    persona: "example_android_14"
    nfqueue_num: 0

  - name: "linux-pool-1"
    ipv6_subnet: "2a01:4f8:c0c:5678::/64"
    count: 1000
    proxy_type: "http"
    port_range: { start: 31000, end: 31999 }
    persona: "example_ubuntu_22_04"
    nfqueue_num: 1
