global:
  state_file_path: /app/state/state.json
  proxy_config_path: /app/config/3proxy.cfg
  ipv6_interface: eno1
  inbound_ipv4_address: "0.0.0.0"
  enable_outbound_e: false

observability:
  health_bind: "127.0.0.1:9090"
  health_interval_sec: 60

handler:
  modify_packets: true
  lab_mutation:
    enable: true
    # ПОДСТАВЬ свои удалённые цели здесь (см. пояснение выше)
    targets:
      - "0.0.0.0/0"
      - "::/0"
    ip_tos: 0x1a
    ipv6_tc: 0x1a
    ttl_override:            # можно оставить пустым: возьмём из "персоны"
    tcp_options: true        # ВКЛ: строим TCP options по персоне
    mss_ipv4: 1460           # "calc" для IPv4
    mss_ipv6: 1440           # "calc" для IPv6

# ФЕЙКОВЫЕ «персоны» — НИЧЕГО общего с реальными ОС.
personas:
  nebula_os_alpha:
    ttl: 61
    window_size: 41264
    tcp_options_layout:
      - { name: "MSS", value: "calc" }
      - { name: "WScale", value: 5 }
      - { name: "SACK" }
      - { name: "Timestamps" }
      - { name: "NOP" }

  kronos_beta:
    ttl: 97
    window_size: 50120
    tcp_options_layout:
      - { name: "MSS", value: "calc" }
      - { name: "SACK" }
      - { name: "NOP" }
      - { name: "WScale", value: 7 }

  test_linux:
    ttl: 64
    window_size: 65535
    tcp_options_layout:
      - { name: "MSS", value: "calc" }
      - { name: "SACK" }
      - { name: "Timestamps" }
      - { name: "WScale", value: 6 }

proxy_groups:
  - name: "pool-1"
    ipv6_subnet: "2a01:4f8:c0c:1234::/64"
    count: 1
    proxy_type: "http"
    port_range: { start: 30000, end: 30000 }  # один порт
    persona: "nebula_os_alpha"                # фейковая персона для LAB
    nfqueue_num: 0

